# Generated by Django 3.2.16 on 2022-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='informations/')),
            ],
        ),
    ]
